### ISSUE TITLE
Tokenizer + POST

### ISSUE THREAD

**Issue by romruben** [RomRuben/TFM#2]
- [x] Frameworks Definition
- [x] Experiment Design
- [x] Implementation
- [x] Execution & Analysis

**Comment by romruben** [comment]
In the first documentation round, i found the following info divided into Tokenizer and POSTagger:

## Tokenizer
- **[A Comparison of 13 Tokenizers on MEDLINE](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.216.2433&rep=rep1&type=pdf)** : This report describes a study on tokenization of MEDLINE abstracts by 13 different software packages that are freely available. 

> Of this study it could extract 13 tools and some ideas for experiments design to analyze tokenizer tools.
- **[Towards Tokenization Evaluation](https://perso.limsi.fr/gabrieli/CV/Publis/Articles/habert-et-al98b.pdf)**

> This study does a  comparative evaluation of Tokenizer tools based on quantitative methods. From it, I could extract some ideas for the experiment design with quantitative approach.
- **[Tweet NLP](http://www.ark.cs.cmu.edu/TweetNLP/)**: Just another tokenizer tool.
- **[NLP Stack](https://github.com/allenai/nlpstack)**: Basic stack of NLP tools.

> Very important link, due to it is a NLP stack that uses many frameworks with differents languages over a facade (stack) written in Python. It is approach given in our papper @fpromero.

## POS Tagging
- **[A comparison of three part-of-speech taggers](http://stp.lingfil.uu.se/exarb/arch/2009_block_vent.pdf)**: This thesis presents a comparison of three part-of-speech taggers, µ-TBL, TnT and HunPOS

> The three analyzed tools used differents methods for tagging the words. Then we could prove what is the best method for a business documents processing.
- **[100 Best GitHub: POS Tagging](http://meta-guide.com/software-meta-guide/100-best-github-part-of-speech-tagging/)**: (alt. link) https://github.com/search?q=part-of-speech-tagging

> too many frameworks, but some can be interesting (it is need to be analyzed)
- **[Survey of POS taggers](http://korpus.dsl.dk/clarin/corpus-doc/pos-survey.pdf)**: This technical report describes WP 2.1’s requirements to part-of-speech (= POS) tagging and provides a survey of existing POS approaches and their suitability. The survey is based on the requirements defined in Section 1. The report finishes with some conclusions on which approach to choose for tagging WP 2.1 corpus texts.

> Of this study can extract the main characteristics of several POSTaggers tools. Each one, has been analyzed by:  availability, features, code, architecture, usability. (Very util link)
- **[Context-less POS tagging with NLTK](http://sujitpal.blogspot.com.es/2014/08/context-less-pos-tagging-with-nltk.html)**:Last week I was handed an interesting task - flagging non-nouns from single word synonyms for concepts in our Medical Ontology. Now, the Part of Speech (POS) tag is not really an intrinsic attribute of a word - rather, the POS is determined by the context in which the word appears. For example, consider the two sentences - "He had an infectious laugh", where laugh is a Noun, and "He will laugh at the joke", where the same word is now a Verb. However, a word with multiple senses (usually) has one dominant sense, so in the absence of my context, we could call that the word's POS. In order to calculate the dominant POS for words, I decided to use the words in the Brown Corpus, a manually tagged text corpus of about 500 articles. The Brown Corpus is available (after nltk.download()) as part of the Natural Language Processing Toolkit (NLTK).

> Util to extract the top words in a text and therefore util for the tagging processing of words. When we are looking for the top terms of a text, one of the firsts process to do is get the filtered words to choose the type as we want, for example all nouns. However these filter can be wrong due to that an important word can be presented by other type, for example an important noun can be presented as a verb. Therefore the context is very important and is something that is important to keep in mind (@fpromero). Related issues #5 #2 #3.
- **[POS Tagging](http://aclweb.org/aclwiki/index.php?title=POS_Tagging_%28State_of_the_art%29)**: A collection of most important POS tagger tools. (Must Read)
- **[A good POS tagger in about 200 lines of Python](https://honnibal.wordpress.com/2013/09/11/a-good-part-of-speechpos-tagger-in-about-200-lines-of-python/)**: Relate link - http://honnibal.github.io/spaCy/

**Comment by romruben** [comment]
Next, it show a provisional list of Tokenizer and POS Tagger frameworks. The main aim is that this list can evolve, from a big list of tools, to a minimum number of tools (5-6 max), limiting the scope of the proofs.

## Tokenizer
- **[NLTK Tokenizer](http://www.nltk.org/api/nltk.tokenize.html)**
- **[OpenNLP Tokenizer](http://opennlp.apache.org/documentation/manual/opennlp.html#tools.tokenizer)**
- **[Mallet Tokenizer](http://mallet.cs.umass.edu/api/cc/mallet/extract/Tokenization.html)**
- ~~**[Specialist NLP Tokenizer](http://lsg3.nlm.nih.gov/LexSysGroup/Projects/textTools/current/apiDoc/gov/nih/nlm/nls/nlp/tokenizer/package-frame.html)**~~ : Only for biomedical domain.
- ~~**Gump tokenizer**~~ : No doc.
- ~~**Dan Melamed’s tokenizer**~~ : No doc.
- ~~**Qtoken**~~ : No doc.
- ~~**UIUC word splitter**~~ : No doc.
- ~~**LT TTT tokenizer**~~ : no maintained since 2000.
- ~~**MedPost tokenizer**~~ : there aren't sufficient info
- ~~**Brill’s POS tagger**~~
- **[Stanford NLP Tokenizer](http://nlp.stanford.edu/software/tokenizer.shtml)**
- ~~**MXPOST tagger**~~
- ~~**[Tweet NLP](https://github.com/brendano/ark-tweet-nlp/blob/master/src/cmu/arktweetnlp/Twokenize.java)**~~: too oriented to tweets.
- **[Deeplearning4j’s](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/text/tokenization/tokenizer/Tokenizer.java)**
- **[spaCy](http://honnibal.github.io/spaCy/)**

## POS Tagger
- **[IMS's TreeTagger](http://www.ims.uni-stuttgart.de/projekte/corplex/TreeTagger/)**
- ~~**[TnT](http://www.coli.uni-saarland.de/~thorsten/tnt/)**~~: Implemented on NLTK.
- ~~**[SVMTool](http://www.lsi.upc.es/~nlp/SVMTool/)**~~ : WTF? :-1: 
- **[Stanford Log-linear Part-Of-Speech Tagger](http://nlp.stanford.edu/software/tagger.shtml)**
- **[Apache UIMA Tagger](http://uima.apache.org/sandbox.html)**
- ~~**[unsupos - Unsupervised Part-ofSpeech Tagging](http://wortschatz.uni-leipzig.de/~cbiemann/software/unsupos.html)**~~ : WTF? :-1: 
- ~~**[Brill Tagger](https://en.wikipedia.org/wiki/Brill_tagger)**~~: is a type of tagger implemented in NLTK.
- **[Sujit Pal's HMM-based tagger](http://sujitpal.blogspot.com/2008/11/ir-math-in-java-hmm-based-pos.html)** (Custom NLP Toolkit):
- **[LingPipe](http://alias-i.com/lingpipe/index.html)**
- **[Jitar](http://github.com/danieldk/jitar)**
- ~~**[µ-TBL](http://www.ling.gu.se/~lager/mutbl.html)**~~ : SICStus Prolog required :-1: .
- ~~**[HunPOS](https://code.google.com/p/hunpos/)**~~ : implemented on NLTK.
- ~~**[spaCy](http://honnibal.github.io/spaCy/)**~~: too simple.

**Comment by romruben** [comment]
After filter the last results, the libs selected are:

## Tokenizer
- **[NLTK Tokenizer](http://www.nltk.org/api/nltk.tokenize.html)**
- **[OpenNLP Tokenizer](http://opennlp.apache.org/documentation/manual/opennlp.html#tools.tokenizer)**
- **[Mallet Tokenizer](http://mallet.cs.umass.edu/api/cc/mallet/extract/Tokenization.html)**
- **[Stanford NLP Tokenizer](http://nlp.stanford.edu/software/tokenizer.shtml)**
- **[Deeplearning4j’s](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/text/tokenization/tokenizer/Tokenizer.java)**

## POS Tagger
- **[IMS's TreeTagger](http://www.ims.uni-stuttgart.de/projekte/corplex/TreeTagger/)**
- **[Stanford Log-linear Part-Of-Speech Tagger](http://nlp.stanford.edu/software/tagger.shtml)**
- **[Apache UIMA Tagger](http://uima.apache.org/sandbox.html)**
- **[Sujit Pal's HMM-based tagger](http://sujitpal.blogspot.com/2008/11/ir-math-in-java-hmm-based-pos.html)** (Custom NLP Toolkit):
- **[LingPipe](http://alias-i.com/lingpipe/index.html)**
- **[Jitar](http://github.com/danieldk/jitar)**

The next step is define the definitive list of frameworks to evaluate. I need a fast review here @fpromero.

**Comment by fpromero** [comment]
It's OK. You can reduce the number of POST Tagger to 5

**Comment by romruben** [comment]
After reading the first comment of [this post](http://www.quora.com/Which-NLP-library-among-the-ones-below-is-most-mature-and-should-be-used-by-a-startup-for-its-NLP-needs). The following POS Tagger list is definitive:
- **[OpenNLP POSTagger](http://opennlp.apache.org/documentation/manual/opennlp.html#tools.postagger)**
- **[NLTK](www.nltk.org/_modules/nltk/tag.html)** : Implements an interface of some POS Tagger libs. (All in one: brill + brill trainer + tnt + hunpos + stanford + hmm + senna + mapping + crf + sequential + nltk)
- **[LingPipe](http://alias-i.com/lingpipe/demos/tutorial/posTags/read-me.html)**

@fpromero 3 frameworks, after we can play with other frameworks via NLTK interfaces.

**Comment by romruben** [comment]
# Frameworks Definition

## Tokenizer
- **[NLTK Tokenizer](http://www.nltk.org/api/nltk.tokenize.html)**
- **[OpenNLP Tokenizer](http://opennlp.apache.org/documentation/manual/opennlp.html#tools.tokenizer)**
- **[Mallet Tokenizer](http://mallet.cs.umass.edu/api/cc/mallet/extract/Tokenization.html)**
- **[Stanford NLP Tokenizer](http://nlp.stanford.edu/software/tokenizer.shtml)**
- **[Deeplearning4j’s](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-scaleout/deeplearning4j-nlp/src/main/java/org/deeplearning4j/text/tokenization/tokenizer/Tokenizer.java)**

## POS Tagger
- **[OpenNLP POSTagger](http://opennlp.apache.org/documentation/manual/opennlp.html#tools.postagger)**
- **[NLTK](www.nltk.org/_modules/nltk/tag.html)** : Implements an interface of some POS Tagger libs. (All in one: brill + brill trainer + tnt + hunpos + stanford + hmm + senna + mapping + crf + sequential + nltk)
- **[LingPipe](http://alias-i.com/lingpipe/demos/tutorial/posTags/read-me.html)**

**Comment by romruben** [comment]
# Experiment Design

## Tokenizer

Evaluate:
- [ ] The execution time
- [ ] Memory consumption
- [ ] String evaluations:
  - [ ] Words with hyphenated compound words (e.g. credit-card)
  - [ ] Words with letters and slashes (e.g. insertion/deletion)
  - [ ] Words with letters and apostrophes (e.g. Ruben's master thesis)
  - [ ] Words with letters and brackets (e.g. CDSS (Clinical Decision support system))
  - [ ] Words with letters and numbers (e.g. 12th)
  - [ ] Words with numbers and one type of puntuationes (e.g. 1.30483,10)
  - [ ] Aritmetical expressions as 8.4-10%
  - [ ] A hypertext markup symbol (e.g. &lt)
  - [ ] URLs (http://www.smile.uclm.es)
  - [ ] Abbreviations (C.D.S.S. / CDSS)
  - [ ] Quoted text ("production costs")

Acknowledgement:
- [A Comparison of 13 Tokenizers on MEDLINE](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.216.2433&rep=rep1&type=pdf)

## POSTagger
- [ ] The execution time
- [ ] Memory consumption 
- [ ] Study the efectivity (Number of well tagged words of all of them) of POSTagger. For it, we need to extract a few corpus from (http://www.nltk.org/nltk_data/) and pre-process for create an scheme with which to compare our results.
- [Using Wikicorpus & NLTK to build a Spanish part-of-speech tagger](http://www.clips.ua.ac.be/pages/using-wikicorpus-nltk-to-build-a-spanish-part-of-speech-tagger)

@fpromero

**Comment by romruben** [comment]
Nltk tokenizer tests results:

| Tokenizer | Expected |  Detected | Success Rate | Time Spent |
| --- | --- | --- | --- | --- |
| TreebankWordTokenizer | 282 | 329 | 0.84% |  11 milliseconds |
| RegxpTokenizer | 282 |  286 |  99% | 1 millisecond |
| WhitespaceTokenizer | 282 | 285 |  99% | 0 milliseconds |
| word_tokenize | 282 | 336 | 81% | 194 milliseconds |
| SpaceTokenizer | 282 | 283 | 99% | 0 milliseconds |
| StanfordTokenizer | 282 | 336 |  81% | 758 milliseconds |
| TextTillingTokenizer |  X | Y | 0,0% | 55 milliseconds |
| PunktSentenceTokenizer | 282 | 13 | 0,04% | 2 milliseconds |

the success rate has no meaning here due to the expected amount is the total number of words separated by spaces. However the time spent is very interesting to evaluate the tokenizer execution time

**Comment by romruben** [comment]
Mallet Tokenizer results:

Expected 282, Obtained 286 in PT-0.011S

**Comment by romruben** [comment]
OpenNLP Tokenizer results:

TokenizerMe expected 282, obtained : 335 in PT-0.166S

**Comment by romruben** [comment]
Se han subido algunas pruebas del framework deeplearning4J pero no dan resultados demasiado buenos, mañana en cuanto pueda pongo datos numéricos.

**Comment by romruben** [comment]
Despues de buscar mucho se va a utilizar para comparar el siguiente corpus:

[http://www.nltk.org/nltk_data/packages/corpora/masc_tagged.zip](http://www.nltk.org/nltk_data/packages/corpora/masc_tagged.zip)

Uno de los corpus disponibles y abiertos de "The Open American National Corpus" (http://www.anc.org/).

**Comment by romruben** [comment]
Vale los POSTaggers probados del framework de NLTK son:
- Standar POSTagger
- Affix POSTagger
- Default POSTagger
- Classifier Based POSTagger
- Unigram Tagger
- Bigram Tagger
- Trigram Tagger
- Ngram Tagger
- Regexp Tagger
- Standford NER POSTagger
- Stanford POSTagger

También se han implementado los siguientes, sin embargo por multiples razones (no implementado aun, errores que tienen, etc) no se ha conseguido obtener los resultados satisfactorios que nos gustaría:
- Brill Tagger : En este momento no nos es útil, lo único que hace es aplicar reglas para una sustitución y etiquetado supuestamente más eficiente. Hace falta suministrarle un tagger inicial como puede ser Default POSTagger y posteriormente definir una serie de reglas de sustitución (tbl.rule.TagRule) y posteriormente inicia el proceso sobre un corpus.
- CRFT Tagger: Requiere la instalación de un paquete externo: 'pip install python-crfsuite'. Por las pruebas que he ido realizando, solicita un corpus de entrenamiento haciendo uso de un modelo ( en el proyecto uso 'model.crf.tagger'), pero este entrenamiento se queda construyendo un grafo ahi infinitamente, haciendo iteraciones del tipo:
  
  ```
    ***** Iteration #1 *****
    Loss: 271752.109732
    Feature norm: 21.000000
    Error norm: 14145.063328
    Active features: 27096
    Line search trials: 3
    Line search step: 0.000947
    Seconds required for this iteration: 59.954
  ```
- Hidden Markov Model Tagger: 
- HunPOS Tagger: En primer lugar, hay que descargar de aquí los modelos: https://code.google.com/p/hunpos/downloads/list y setear la variable de entorno -> HUNPOS_TAGGER. Posteriormente tras realizar las pruebas, hay un error (que asumo se encuentra en la propia libreria, por las pruebas realizadas) que desemboca en una excepción: "BROKEN PIPEN".
- Senna Tagger / Senna Chunk Tagger / Senna NER Tagger: Para comenzar hay que descargar toda la suite de http://ronan.collobert.com/senna/download.html (nltk solo funciona aquí tb de wrapper). El problema que he encontrado ha sido el hecho de que el nltk funciona de "semi-wrapper", por lo que, si existen limitaciones internas de Senna hay que ir al codigo original. Y este ha sido el caso, cada etiquetado de palabras tiene un máximo de 1024 tokens (entendiendo que para ellos un token es una letra a pesar de que les mandes una lista de palabras), para ello hay que acceder a la suite e ir a SENNA_main.c y modificar la macro MAX_SENTENCE_SIZE. Tras hacerlo y recompilar toda la suite en C, el problema del máximo ha continuado y no ha surtido efecto. Por lo que este POSTagger solo puede etiquetar palabras cuyo numero de carácteres totales sea 1024.
- TnT Tagger: Por más que he probado, no consigo que termine el entrenamiento con la misma coleccion que aplico al resto de taggers.
- Stanford Tagger: Realmente es un facade para usar posteriormente el StandFord POSTagger o el Stanford NER Tagger. Por tanto lo he metido aquí porque es inútil.

**Comment by romruben** [comment]
Los resultados obtenidos por parte de los que se han probado son (incluido el entrenamiento, ya que algunos lo piden en tiempo de ejecución, otros usan modelos ya creados): 

| Tagger | Expected | Obtained | Accurancy | Time | Observations |
| --- | --- | --- | --- | --- | --- |
| Standard POSTagger | 3744 | 2767 | 73.90 % | 4.94 s | (No ha requerido entrenamiento) |
| Affix Tagger | 3744 | 478 | 12.77 % | 0.22 s | (Entrenado en ejecución) |
| Default POS Tagger | 454 | 454 | 100 % | 0.008 s | Solo ha taggeado los NN |
| Classifier Based POSTagger | 3744 | 1704 | 45.51 % | 40.37 s | (Entrenado en ejecución) |
| Unigram Tagger | 3744 | 1588 | 42.41 % | 0.45 s | (Entrenado en ejecución) |
| Bigram Tagger | 3744 | 1591 | 42.49 % | 1.45 s | backoff Unigram Tagger |
| Trigram Tagger | 3744 | 1595 | 42.60 % | 1,56 s | backoff Unigram Tagger |
| Ngram Tagger | 3744 | 1588 | 42.41 % | 1.67 s | backoff Unigram Tagger y N = 5 |
| Regexp Tagger | 454 | 452 | 99.56 % | 0,011 s | Solo ha taggeado los NN |
| Standford POSTagger | 3744 | 2940 | 78.53 % | 7,99 s | (usa modelo por idioma) |

Porfavor, aunque lo parezca, no lo entiendas como una tabla comparativa sino resumen. En ocasiones como en el default pos tagger, regexp etc. no se han podido comparar al resto puesto que solo van tag a tag recuperando y etiquetando lo que le pedimos.

De los que te he dicho que se han podido probar bien, hay uno que no lo he puesto aquí debido a que su función no es hacer un tag del tipo de palabra sino de "significado". Cuando digo significado digo que detecta si una palabra se refiere a una localización, un pais etc, y es el llamado Standford NER POSTagger. De esta manera me taggea por ejemplo "Detroit" como "LOCATION". Simplemente, está ahí y es interesante.

**Comment by romruben** [comment]
La evaluación de OpenNLP con los dos modelos oficiales es:

```
test OpenNLP, Model: src/main/resources/en-pos-maxent.bin, Duration: PT-1.75S, Expected: 3746, Obtained: 3251, Accurancy: 86.79 %
test OpenNLP, Model: src/main/resources/en-pos-perceptron.bin, Duration: PT-0.736S, Expected: 3746, Obtained: 2979, Accurancy: 79.52 %
```

**Comment by romruben** [comment]
Debido a un fallo no detectado ayer con los tags y otro con los saltos de linea, los resultados que posteé no son del todo correctos, los verdaderos tras verificarlo, encontrar el fallo y corregirlo son:

```
test OpenNLP, Model: src/main/resources/en-pos-maxent.bin, Duration: PT-18.881S, Expected: 3745, Obtained: 3370, Accurancy: 89.99 %
test OpenNLP, Model: src/main/resources/en-pos-perceptron.bin, Duration: PT-9.98S, Expected: 3745, Obtained: 3205, Accurancy: 85.58 %
```

**Comment by romruben** [comment]
Ya se ha finalizado las pruebas con el ultimo POSTagger, LingPipe, con el siguiente resultado:

```
test LingPipeTests, Model: HiddenMarkovModel, Duration: PT-0.68S, Expected: 3745, Obtained: 2357, Accurancy: 62.94 %
```
