### ISSUE TITLE
Weighting Terms

### ISSUE THREAD

**Issue by romruben** [RomRuben/TFM#3]
- [x] Frameworks Definition
- [x] Experiment Design
- [x] Implementation
- [x] Execution & Analysis

**Comment by romruben** [comment]
I cant find a specific framework or library to measure the weight of a term. The best info that i could find, is in Theanu project. I need some orientation to continue: i search the development of algorithms (therefore we evaluates the algorithms but not frameworks) or how i must search this, because i don't find anything. @fpromero

**Comment by fpromero** [comment]
It's difficult to find specific weighting schemes in the most common open source NLP's APIS, but, your comment "Sí es verdad que tienen POSTagger + Tokenizer y un par de fórmulas para asignarle el peso a los términos, pero muy básicas." suggests the possibility to evaluate some common weighting schemes.

There are two alternatives:
1. To ignore this tasks, but i think, labelling documents is one of the most important tasks in the docpath project.
2. To evaluate these basic measures  (for example , lucene measures) and to compare with tehanu sofware, previously, tehanu has to be published in github. This is the most adequate alternative.

**Comment by romruben** [comment]
I agree with you, the second option is the best.

**Comment by romruben** [comment]
# Frameworks Definition

# Weighting Terms
- Theanu
- NLTK
- OpenNLP
- LingPipe

@fpromero

**Comment by romruben** [comment]
# Experiment Design

## Weighting Terms

Evaluate:
- [ ] The execution time
- [ ] Memory consumption
- [ ] Tf-df
- [ ] Tf-idf

@fpromero

**Comment by fpromero** [comment]
OK
