### ISSUE TITLE
Language Detection

### ISSUE THREAD

**Issue by romruben** [RomRuben/TFM#4]
- [x] Frameworks Definition
- [x] Experiment Design
- [x] Implementation
- [x] Execution & Analysis

**Comment by romruben** [comment]
In the first documentation round, i found the following info about language detection.

## Language Detection
- **[Language-Detection](https://github.com/shuyo/language-detection)**: This is a language detection library implemented in plain Java. Generate language profiles from Wikipedia abstract xml, Detect language of a text using naive Bayesian filter, 99% over precision for 53 languages.

> The library that we used in the docpath project.
- **[Language Identification tools](odur.let.rug.nl/~vannoord/TextCat/competitors.html)**: A list of language identification tools. Related link ([Language Identification tools](www.soft-switch.org/downloads/speech/lang_guess/lang_guess/competitors.html)).

> This site classifies the tools by number of languages supported and license.
- **[Language Identification Tools](www.aclweb.org/aclwiki/index.php?title=Language_Identification_Tools):** A listing of language identification tools. Language identification can mean both identifiying text type (e.g. news vs literature) and language (e.g. English vs Frisian vs Dutch). Most of these tools require training on a big corpus (see [List of resources by language](http://www.aclweb.org/aclwiki/index.php?title=List_of_resources_by_language)  for corpora per language), but many come with some prebuilt language models.

> This site classifies the tools by solving strategy.
- **[Langid.py](https://github.com/saffsd/langid.py)**: Stand-alone language identification system.
- **[Wikipedia Entry: Language Identification](https://en.wikipedia.org/wiki/Language_identification)** : Wikipedia page about Language identification.

> This wikipedia entry has a list of most popular libraries and web services used for language identification.
- **[ANTLR](www.antlr.org/download.html)**: ANTLR (ANother Tool for Language Recognition) is a powerful parser generator for reading, processing, executing, or translating structured text or binary files. It's widely used to build languages, tools, and frameworks. From a grammar, ANTLR generates a parser that can build and walk parse trees. 

> Interesting tool.

**Comment by romruben** [comment]
This is the candidate frameworks:

## Language Detection
- **[Language-Detection](https://github.com/shuyo/language-detection)**: This is a language detection library implemented in plain Java. Generate language profiles from Wikipedia abstract xml, Detect language of a text using naive Bayesian filter, 99% over precision for 53 languages. (**must**).
- **[Textcat for Java](http://textcat.sourceforge.net/)** : The text analysis algorithm is based on the classification technique described in Cavnar & Trenkle, "N-Gram-Based Text Categorization".  Also : http://software.wise-guys.nl/libtextcat/.
- **[Textcat for Python](http://thomas.mangin.com/data/source/ngram.py)** : An simple script with the textcat language detection process.
- **[Langid.py](https://github.com/saffsd/langid.py)**.
- **[Guess Language](https://bitbucket.org/spirit/guess_language)**.
- **[Nutch LanguageIdentifier](https://wiki.apache.org/nutch/LanguageIdentifier)**.
- **[cld.js](https://github.com/jaukia/cld-js)** : Detect the langugage of any piece of text — the text goes in and a language comes out. This is a Javascript port of the Compact Language Detector from Chromium.
- **[LC4J](olivo.net/2009/08/lc4j/)**.
- **[ANTLR](http://www.antlr.org/download.html)**.

**Comment by romruben** [comment]
# Frameworks Definition

## Language Detection
- **[Language-Detection](https://github.com/shuyo/language-detection)**: This is a language detection library implemented in plain Java. Generate language profiles from Wikipedia abstract xml, Detect language of a text using naive Bayesian filter, 99% over precision for 53 languages. (**must**).
- **[Langid.py](https://github.com/saffsd/langid.py)** : Stand-alone language identification system. 97 languages.
- **[Guess Language](https://bitbucket.org/spirit/guess_language)** : 66 languages but, it can generates a new models.
- **[LC4J](http://olivo.net/2009/08/lc4j/#download)** : 153 languages.

**Comment by romruben** [comment]
# Experiment Design

## Language Detection
- [ ] The execution time
- [ ] Memory consumption
- [ ] Evaluate the language detection with a set of documents in multiple languages. The framework measure is: correctly detected languages / all documents.

@fpromero

**Comment by fpromero** [comment]
OK

**Comment by fpromero** [comment]
First, makes this one the first because it is important to detect language previously to POST

**Comment by romruben** [comment]
Ok, if u want, close this issue, and i create other for implementations and analysis.

**Comment by romruben** [comment]
Finally this weekend, i haven't been able to work except this afternoon. However i have finished the first pocs with 2 frameworks:
- [langidPy](https://github.com/RomRuben/TFM/tree/master/tfm_projects/langdetection/langidPy)
- [language_detection](https://github.com/RomRuben/TFM/tree/master/tfm_projects/langdetection/language_detection)

Checks it when you want, and if you have any problem write me.

**Comment by romruben** [comment]
- [Guess Language Framework](https://github.com/RomRuben/TFM/tree/master/tfm_projects/langdetection/guess_language) Implementation added.

**Comment by romruben** [comment]
- [lc4J Framework](https://github.com/RomRuben/TFM/tree/master/tfm_projects/langdetection/lc4j) implementation added.

With this, i finish the first implementation of all language detection frameworks. Tomorrow i will refactor and improve the documentation of the language detection. And on Wednesday i will start with the Tokenizer frameworks.

The framework with best preliminary results in tests is that we used in the Docpath project (the bayesian network framework, used by google in some projects).

**Comment by romruben** [comment]
I have been improving the framework implementation, and documenting some parts of the project. I ran some tests in order to determine de success rate in the detection of Spanish and English documents with default profiles and models. The reference files are those we used in the docpath project. And the results are the following:

| Framework | Expected |  Detected | Success Rate | Time Spent |
| --- | --- | --- | --- | --- |
| Guess_language | 240 | 201 | 0.84% | 5.83 s |
| Langid.py | 240 | 220 | 0.91% | 4.99 s |
| Language_detection | 240 | 238 | 0.99% | 2.10 s |
| Lc4j | 240 | 138 | 0.55% | 2.30 s |

Sometimes, the language_detection framework,  reaches the 100% of success rate.
